#!/usr/bin/env python3
"""Unit tests for scripts/docs-index.py (T-037).

Run with either:
    python3 -m unittest scripts.tests.test_docs_index
    python3 scripts/tests/test_docs_index.py

Hermetic: each test builds an isolated docs/ fixture in a tempdir and runs the
real index generator against it (with the shipped schema + a fixture
trace-model). The live repo is never touched.
"""

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[1]
SCRIPT = SCRIPTS_DIR / "docs-index.py"
SCHEMA = SCRIPTS_DIR / "docs-meta.schema.json"

OK, DRIFT, USAGE = 0, 1, 2

DEFAULT_MODEL = {
    "schema": 1,
    "types": ["vision", "requirement", "work-item", "iteration-plan",
              "use-case", "test-case", "decision"],
    "trace_edges": [
        {"from": "requirement", "to": "vision", "relation": "traces-from"},
        {"from": "work-item", "to": "requirement", "relation": "traces-from"},
        {"from": "test-case", "to": "requirement", "relation": "traces-from"},
        {"from": "use-case", "to": "requirement", "relation": "traces-from"},
    ],
    "coverage_rules": [
        {"type": "requirement", "relation": "verified-by",
         "target": "test-case", "severity": "required"},
        {"type": "work-item", "relation": "traces-from",
         "target": "requirement", "severity": "required"},
    ],
}


def write_instance(docs, relpath, *, frontmatter, body=""):
    path = docs / relpath
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["---", *frontmatter, "---", "", body]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_model(root: Path, model=None):
    model = model if model is not None else DEFAULT_MODEL
    p = root / "trace-model.json"
    p.write_text(json.dumps(model), encoding="utf-8")
    return p


def run(docs, *, model=None, mode=None, expect=None, out=None, extra=None):
    cmd = [sys.executable, str(SCRIPT),
           "--docs", str(docs),
           "--schema", str(SCHEMA)]
    if model is not None:
        cmd += ["--model", str(model)]
    if mode is not None:
        cmd += [mode]
    if out is not None:
        cmd += ["--out", str(out)]
    if extra:
        cmd += extra
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if expect is not None:
        assert proc.returncode == expect, (
            f"expected {expect}, got {proc.returncode}\n"
            f"stdout={proc.stdout}\nstderr={proc.stderr}")
    return proc


class _FixtureBase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.docs = self.root / "docs"
        self.docs.mkdir()
        self.model = write_model(self.root)

    def tearDown(self):
        self._tmp.cleanup()

    def vision(self, **kw):
        write_instance(self.docs, "product/vision.md", frontmatter=[
            "type: vision", "id: VIS-001", "title: Vision",
            "status: approved"], **kw)

    def make_test_case(self, iid="TC-031", **kw):
        write_instance(self.docs, f"tests/{iid}.md", frontmatter=[
            "type: test-case", f"id: {iid}", "title: Test",
            "status: implemented"], **kw)

    def make_req(self, iid="REQ-014", status="approved",
                 traces_from=("VIS-001",), verified_by=()):
        fm = ["type: requirement", f"id: {iid}",
              f"title: Requirement {iid}", f"status: {status}"]
        if traces_from:
            fm.append(f"traces-from: [{', '.join(traces_from)}]")
        if verified_by:
            fm.append(f"verified-by: [{', '.join(verified_by)}]")
        write_instance(self.docs, f"changes/{iid}.md", frontmatter=fm)


class BasicGenerationTests(_FixtureBase):
    def test_empty_docs_emits_marker_and_zero_count(self):
        proc = run(self.docs, model=self.model, mode="--stdout", expect=OK)
        self.assertIn("<!-- Generated by scripts/docs-index.py", proc.stdout)
        self.assertIn("0 typed instance(s) discovered", proc.stdout)
        self.assertIn("## Trace Web", proc.stdout)
        self.assertIn("## Coverage", proc.stdout)

    def test_write_creates_index_file(self):
        self.vision()
        proc = run(self.docs, model=self.model, expect=OK)
        index = self.docs / "INDEX.md"
        self.assertTrue(index.is_file())
        text = index.read_text(encoding="utf-8")
        self.assertIn("VIS-001 — Vision", text)
        # Assert the script reports writing the index, without pinning the
        # absolute path prefix — the OS may report the tmp dir through a
        # resolved symlink (/var -> /private/var on macOS).
        self.assertRegex(proc.stdout, r"wrote\b.*INDEX\.md")

    def test_idempotent_regeneration(self):
        """Re-running on unchanged inputs produces a byte-identical file."""
        self.vision()
        self.make_test_case()
        self.make_req(verified_by=("TC-031",))
        run(self.docs, model=self.model, expect=OK)
        first = (self.docs / "INDEX.md").read_text(encoding="utf-8")
        run(self.docs, model=self.model, expect=OK)
        second = (self.docs / "INDEX.md").read_text(encoding="utf-8")
        self.assertEqual(first, second)


class TraceWebTests(_FixtureBase):
    def test_traced_by_inverse_derived_from_traces_from(self):
        """A vision the requirement traces-from should show the requirement's id
        under its ``traced-by`` line, even though the vision itself does not
        carry one (the inverse is derived, never authored)."""
        self.vision()
        self.make_req(verified_by=("TC-031",))
        self.make_test_case()
        proc = run(self.docs, model=self.model, mode="--stdout", expect=OK)
        # The vision should list REQ-014 in its traced-by inverse.
        # Look for the line under the vision block.
        text = proc.stdout
        # The inverse line lives between the vision label and the next bullet.
        self.assertIn("**VIS-001 — Vision**", text)
        # Crude but sufficient: traced-by REQ-014 must appear in the body.
        self.assertIn("traced-by: REQ-014", text)

    def test_instances_grouped_by_type_in_canonical_order(self):
        """vision must render before requirement, and requirement before
        test-case, mirroring the OpenUP flow."""
        self.vision()
        self.make_req(verified_by=("TC-031",))
        self.make_test_case()
        proc = run(self.docs, model=self.model, mode="--stdout", expect=OK)
        text = proc.stdout
        vi = text.index("### vision")
        ri = text.index("### requirement")
        ti = text.index("### test-case")
        self.assertLess(vi, ri)
        self.assertLess(ri, ti)


class CoverageSectionTests(_FixtureBase):
    def test_unverified_requirement_appears_as_gap(self):
        self.vision()
        self.make_req()  # no verified-by
        proc = run(self.docs, model=self.model, mode="--stdout", expect=OK)
        text = proc.stdout
        self.assertIn("requirement → verified-by → test-case", text)
        self.assertIn("0 of 1 covered (1 gap)", text)
        self.assertIn("REQ-014", text)

    def test_fully_covered_set_reports_no_gaps(self):
        self.vision()
        self.make_test_case()
        self.make_req(verified_by=("TC-031",))
        proc = run(self.docs, model=self.model, mode="--stdout", expect=OK)
        self.assertIn("1 of 1 covered (0 gaps)", proc.stdout)


class CheckModeTests(_FixtureBase):
    def test_check_passes_when_committed_index_matches(self):
        self.vision()
        run(self.docs, model=self.model, expect=OK)
        proc = run(self.docs, model=self.model, mode="--check", expect=OK)
        self.assertIn("in sync", proc.stdout)

    def test_check_fails_when_index_is_stale(self):
        self.vision()
        run(self.docs, model=self.model, expect=OK)
        # Mutate the committed index — drift.
        (self.docs / "INDEX.md").write_text("stale\n", encoding="utf-8")
        proc = run(self.docs, model=self.model, mode="--check", expect=DRIFT)
        self.assertIn("stale", proc.stderr)

    def test_check_fails_when_index_is_missing(self):
        self.vision()
        # No prior write — INDEX.md is absent.
        proc = run(self.docs, model=self.model, mode="--check", expect=DRIFT)
        self.assertIn("missing", proc.stderr)


class DegradeModeTests(_FixtureBase):
    def test_missing_model_still_renders_trace_web(self):
        """Without the model, no coverage section content — but the trace web
        still renders so a fresh project before its first
        ``build-trace-model.py`` run is not blocked."""
        self.vision()
        bogus = self.root / "no-such-model.json"
        proc = run(self.docs, model=bogus, mode="--stdout", expect=OK)
        self.assertIn("VIS-001 — Vision", proc.stdout)
        self.assertIn("No required-coverage rules", proc.stdout)


if __name__ == "__main__":
    unittest.main()
