#!/usr/bin/env python3
"""Derived work-product trace index (T-037).

Regenerates ``docs/INDEX.md`` from the typed work-product instances under
``docs/`` and the KB-derived ``scripts/trace-model.json``. The index is the
**derived view** of the work-product trace web — the work-product-tier analogue
of ``.openup/board.json``: never authored by a human or model, regenerated
byte-deterministically from the same inputs ``check-docs.py`` reads.

What the index carries:

  * **Trace web (by type)** — for each spine type (vision · requirement ·
    work-item · iteration-plan · use-case · test-case · decision), a sorted
    list of instances with their authored ``traces-from`` and the **derived
    ``traced-by`` inverse** (downstream work products that trace from this
    one). The inverse is computed here; no instance hand-writes it.
  * **Coverage summary** — one line per required-coverage rule, with the count
    of covered vs gap instances and the file paths of the gaps. Sources:
    ``trace-model.json``'s ``coverage_rules`` (T-035).
  * **Generation marker** — a sentinel header (``<!-- Generated by
    scripts/docs-index.py — do not edit -->``) so reviewers, humans, and
    write-fence-style checks all know this file is owned by the script.

Design rules (match other ``scripts/openup-*.py`` / ``check-docs.py`` tools):
  * Deterministic. Never invokes a model. Python standard library only.
  * Idempotent: re-running on unchanged inputs produces a byte-identical file.
  * Reuses the validator's frontmatter parser + instance discovery so the
    index and ``check-docs.py`` cannot disagree on what counts as an instance.

Subcommands / modes:
  (default)   Write ``docs/INDEX.md`` and print a one-line summary.
  --stdout    Print the index to stdout; do not write the file.
  --check     Regenerate in memory and compare to the committed file; exit 1
              on drift. Used by CI / the project-side check-docs hook.

Exit codes:
  0  success (or ``--check``: in sync)
  1  ``--check``: committed docs/INDEX.md is stale / drifted
  2  usage / environment error (missing schema / docs dir)
"""

import argparse
import importlib.util
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SCHEMA_PATH = SCRIPT_DIR / "docs-meta.schema.json"
TRACE_MODEL_PATH = SCRIPT_DIR / "trace-model.json"

EXIT_OK = 0
EXIT_DRIFT = 1
EXIT_USAGE = 2

GEN_MARKER = "<!-- Generated by scripts/docs-index.py — do not edit -->"

# Load check-docs.py via importlib so we share its parser, discovery, and the
# ``COVERED_STATUSES`` set. The two MUST agree on what counts as an instance
# and on which statuses participate in coverage — that is one of the points of
# this script's "if it's deterministic, the harness does it" rule.
_CHECK_PATH = SCRIPT_DIR / "check-docs.py"
_spec = importlib.util.spec_from_file_location("check_docs", _CHECK_PATH)
check_docs = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_docs)  # type: ignore[union-attr]


# Render order matches the OpenUP work-product flow: producers above
# consumers, with `decision` last as an annotation type.
RENDER_ORDER = (
    "vision",
    "requirement",
    "use-case",
    "work-item",
    "iteration-plan",
    "test-case",
    "decision",
)


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def load_model(path: Path) -> dict:
    """``trace-model.json`` is best-effort here — without it, we still render
    the index (no coverage section, no upstream-type direction), so a fresh
    project before its first ``build-trace-model.py`` run is not blocked."""
    try:
        return load_json(path)
    except (OSError, json.JSONDecodeError):
        return {}


def build_id_index(instances):
    """``id -> [(type, relpath), ...]`` for every typed instance with an id."""
    out = {}
    for rel, fm in instances:
        iid = fm.get("id")
        if isinstance(iid, str) and iid:
            out.setdefault(iid, []).append((fm.get("type"), rel))
    return out


def derive_traced_by(instances, id_index):
    """For each id, the sorted list of *other* ids that ``traces-from`` it.

    Pure derivation: never reads or writes the instance's own ``traced-by``
    field. The schema reserves that key as derived; the v1 implementation
    surfaces the inverse in this index file only and does not write it back
    into instance frontmatter (avoids cross-lane edit conflicts).
    """
    inv = {iid: set() for iid in id_index}
    for _, fm in instances:
        src = fm.get("id")
        if not isinstance(src, str) or not src:
            continue
        for ref in _as_list(fm.get("traces-from")):
            if ref in inv:
                inv[ref].add(src)
    return {iid: sorted(s) for iid, s in inv.items()}


def _as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def _instance_label(fm) -> str:
    """``ID — Title`` if both exist; otherwise whichever is present; else ``?``."""
    iid = fm.get("id")
    title = fm.get("title")
    if iid and title:
        return f"{iid} — {title}"
    return iid or title or "?"


def render_trace_web(instances_by_type, traced_by, docs_relroot: str):
    """Return the ``## Trace Web`` markdown section."""
    lines = ["## Trace Web", ""]
    seen_any = False
    for typ in RENDER_ORDER:
        bucket = instances_by_type.get(typ, [])
        if not bucket:
            continue
        seen_any = True
        lines.append(f"### {typ} ({len(bucket)})")
        lines.append("")
        for rel, fm in bucket:
            label = _instance_label(fm)
            status = (fm.get("status") or "—").lower()
            lines.append(f"- **{label}** · `{status}` · "
                         f"[{rel}]({_link_target(rel, docs_relroot)})")
            tf = _as_list(fm.get("traces-from"))
            if tf:
                lines.append(f"  - traces-from: {', '.join(sorted(tf))}")
            iid = fm.get("id")
            inv = traced_by.get(iid, []) if iid else []
            if inv:
                lines.append(f"  - traced-by: {', '.join(inv)}")
            vb = _as_list(fm.get("verified-by"))
            if vb:
                lines.append(f"  - verified-by: {', '.join(sorted(vb))}")
        lines.append("")
    if not seen_any:
        lines.append("_No typed work-product instances under `docs/` yet._")
        lines.append("")
    return lines


def _link_target(rel: str, docs_relroot: str) -> str:
    """Render a docs-relative link target (``docs/foo.md`` -> ``foo.md``)."""
    prefix = f"{docs_relroot}/"
    if rel.startswith(prefix):
        return rel[len(prefix):]
    return rel


def render_coverage(coverage_findings, rules):
    """Return the ``## Coverage`` markdown section.

    Rules are listed in their model order; each renders a one-line summary
    ("3 of 5 covered") and, when there are gaps, a bullet list of the missing
    instances with their file paths.
    """
    lines = ["## Coverage", ""]
    if not rules:
        lines.append("_No required-coverage rules defined "
                     "(`trace-model.json` missing or empty)._")
        lines.append("")
        return lines

    # Index gaps by (type, relation, target) so we render them rule-by-rule.
    gap_by_rule = {}
    for finding in coverage_findings:
        key = finding["rule_key"]
        gap_by_rule.setdefault(key, []).append(finding)

    for rule in rules:
        key = (rule["type"], rule["relation"], rule["target"])
        severity = (rule.get("severity") or "required").lower()
        gaps = gap_by_rule.get(key, [])
        applicable = rule.get("applicable", 0)
        covered = applicable - len(gaps)
        lines.append(
            f"- **{rule['type']} → {rule['relation']} → {rule['target']}** "
            f"({severity}): {covered} of {applicable} covered "
            f"({len(gaps)} gap{'s' if len(gaps) != 1 else ''})."
        )
        for g in gaps:
            lines.append(f"  - {g['label']} — `{g['file']}`")
    lines.append("")
    return lines


def evaluate_coverage(instances, id_index, model):
    """Return (findings, rules_with_counts).

    Each finding is ``{"rule_key", "label", "file"}``; each rule gets an
    ``applicable`` count so the summary line can render "N of M covered".
    """
    rules_in = model.get("coverage_rules") or []
    if not rules_in:
        return [], []

    # Count applicable instances per rule (covered statuses + matching type),
    # and emit a gap for each unmet one.
    rules = []
    findings = []
    for rule in rules_in:
        typ = rule.get("type")
        relation = rule.get("relation")
        target = rule.get("target")
        severity = (rule.get("severity") or "required").lower()
        key = (typ, relation, target)
        applicable = 0
        for rel, fm in instances:
            if fm.get("type") != typ:
                continue
            status = (fm.get("status") or "").lower()
            if status and status not in check_docs.COVERED_STATUSES:
                continue
            applicable += 1
            refs = _as_list(fm.get(relation))
            covered = False
            for ref in refs:
                for ref_type, _ in id_index.get(ref, []):
                    if ref_type == target:
                        covered = True
                        break
                if covered:
                    break
            if not covered:
                findings.append({
                    "rule_key": key,
                    "label": _instance_label(fm),
                    "file": rel,
                    "severity": severity,
                })
        rules.append({
            "type": typ, "relation": relation, "target": target,
            "severity": severity, "applicable": applicable,
        })
    findings.sort(key=lambda f: (f["rule_key"], f["file"]))
    return findings, rules


def discover_instances_rel(docs_dir: Path, spine_types):
    """Yield ``(relpath_from_docs_parent, frontmatter)`` for every instance."""
    parent = docs_dir.parent
    for path, fm in check_docs.discover_instances(docs_dir, spine_types):
        rel = str(path.relative_to(parent)) \
            if parent in path.parents else str(path)
        yield rel, fm


def build_index(docs_dir: Path, schema: dict, model: dict) -> str:
    """Return the full INDEX.md text (deterministic, idempotent)."""
    spine_types = set(model.get("types") or
                      schema["properties"]["type"]["enum"])

    instances = list(discover_instances_rel(docs_dir, spine_types))
    id_index = build_id_index(instances)
    traced_by = derive_traced_by(instances, id_index)

    by_type = {}
    for rel, fm in instances:
        by_type.setdefault(fm.get("type"), []).append((rel, fm))
    for bucket in by_type.values():
        bucket.sort(key=lambda x: ((x[1].get("id") or ""), x[0]))

    coverage, rules = evaluate_coverage(instances, id_index, model)

    docs_relroot = docs_dir.name  # links land relative to docs/

    out_lines = [
        GEN_MARKER,
        "",
        "# Work-Product Trace Index",
        "",
        "Derived view of the OpenUP work-product trace web for this project. "
        "Generated by `scripts/docs-index.py` (T-037) from the typed "
        "instances under `docs/` and the KB-derived `trace-model.json` "
        "(T-035). Do **not** hand-edit — re-run the generator instead.",
        "",
        f"_{len(instances)} typed instance(s) discovered._",
        "",
    ]
    out_lines.extend(render_trace_web(by_type, traced_by, docs_relroot))
    out_lines.extend(render_coverage(coverage, rules))
    return "\n".join(out_lines).rstrip() + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--docs", help="docs/ directory to index "
                        "(default: ./docs)")
    parser.add_argument("--schema", help="override docs-meta.schema.json path")
    parser.add_argument("--model", help="override trace-model.json path")
    parser.add_argument("--out", help="override docs/INDEX.md output path")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--stdout", action="store_true",
                      help="print the index to stdout; do not write a file")
    mode.add_argument("--check", action="store_true",
                      help="compare committed docs/INDEX.md to a fresh "
                           "generation; exit 1 on drift")
    args = parser.parse_args(argv)

    docs_dir = Path(args.docs).resolve() if args.docs \
        else Path("docs").resolve()
    schema_path = Path(args.schema) if args.schema else SCHEMA_PATH
    model_path = Path(args.model) if args.model else TRACE_MODEL_PATH

    if not docs_dir.is_dir():
        print(f"error: docs directory not found: {docs_dir}", file=sys.stderr)
        return EXIT_USAGE
    try:
        schema = load_json(schema_path)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"error: cannot load schema {schema_path}: {exc}", file=sys.stderr)
        return EXIT_USAGE
    model = load_model(model_path)

    text = build_index(docs_dir, schema, model)
    out_path = Path(args.out).resolve() if args.out \
        else docs_dir / "INDEX.md"

    if args.stdout:
        sys.stdout.write(text)
        return EXIT_OK

    if args.check:
        if not out_path.is_file():
            print(f"drift: {out_path} is missing; run docs-index.py",
                  file=sys.stderr)
            return EXIT_DRIFT
        current = out_path.read_text(encoding="utf-8")
        if current != text:
            print(f"drift: {out_path} is stale; re-run docs-index.py",
                  file=sys.stderr)
            return EXIT_DRIFT
        print(f"docs/INDEX.md in sync")
        return EXIT_OK

    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path}")
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
